import sys
import ROOT
import numpy as np
from uncertainties import ufloat
import matplotlib.pyplot as plt
ROOT.gROOT.SetBatch(True)

def main(argv):
    ROOT.gStyle.SetOptStat(0)

    f_sig = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_10/post_sel_tree_bdt_0.0.root")
    f_ws = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_3/post_sel_tree_bdt_0.0.root")
    f_rs = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_2/post_sel_tree_bdt_0.0.root")
    f_BuDDKp = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_100/post_sel_tree_bdt_0.0.root")
    f_BdDDKp = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_110/post_sel_tree_bdt_0.0.root")
    f_BsDDKp = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_120/post_sel_tree_bdt_0.0.root")
    f_BuDDK0 = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_130/post_sel_tree_bdt_0.0.root")
    f_BuDD = ROOT.TFile("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_150/post_sel_tree_bdt_0.0.root")

    t_sig = f_sig.Get("DecayTree")
    t_ws = f_ws.Get("DecayTree")
    t_rs = f_rs.Get("DecayTree")
    t_BuDDKp = f_BuDDKp.Get("DecayTree")
    t_BdDDKp = f_BdDDKp.Get("DecayTree")
    t_BsDDKp = f_BsDDKp.Get("DecayTree")
    t_BuDDK0 = f_BuDDK0.Get("DecayTree")
    t_BuDD = f_BuDD.Get("DecayTree")

    t_BDDKp = ROOT.TChain("DecayTree")
    t_BDDKp.Add("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_100/post_sel_tree_bdt_0.0.root")
    t_BDDKp.Add("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_110/post_sel_tree_bdt_0.0.root")
    t_BDDKp.Add("/panfs/felician/B2Ktautau/workflow/create_post_selection_tree/Species_120/post_sel_tree_bdt_0.0.root")

    N_comb_00 = 18340524
    N_comb_09 = 216974
    N_comb_099 = 10624
    N_comb_0999 = 170

    nbins = 100

    # Cocktail MC decays
    h_cocktail_1 = ROOT.TH1D("h_cocktail_1", "h_cocktail_1", nbins, 4000, 9000)
    h_cocktail_2 = ROOT.TH1D("h_cocktail_2", "h_cocktail_2", nbins, 4000, 9000)
    h_cocktail_3 = ROOT.TH1D("h_cocktail_3", "h_cocktail_3", nbins, 4000, 9000)
    h_cocktail_4 = ROOT.TH1D("h_cocktail_4", "h_cocktail_4", nbins, 4000, 9000)
    h_cocktail_5 = ROOT.TH1D("h_cocktail_5", "h_cocktail_5", nbins, 4000, 9000)

    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_1", "species == 100")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_2", "species == 101")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_3", "species == 102")
    t_BdDDKp.Draw("df_Bp_M >> h_cocktail_4", "species == 110")
    t_BsDDKp.Draw("df_Bp_M >> h_cocktail_5", "species == 120")

    c_cocktail = ROOT.TCanvas()
    c_cocktail.cd()
    h_cocktail_1.GetXaxis().SetTitle("m_{B} (MeV)")
    h_cocktail_1.GetYaxis().SetTitle("Normalized entries / (50 MeV)")
    h_cocktail_1.SetTitle("Before BDT cuts")
    h_cocktail_1.SetLineColor(1)
    h_cocktail_2.SetLineColor(4)
    h_cocktail_3.SetLineColor(2)
    h_cocktail_4.SetLineColor(8)
    h_cocktail_5.SetLineColor(6)
    h_cocktail_1.Scale(11540./h_cocktail_1.Integral())
    h_cocktail_2.Scale(1513./h_cocktail_2.Integral())
    h_cocktail_3.Scale(1275./h_cocktail_3.Integral())
    h_cocktail_4.Scale(11177./h_cocktail_4.Integral())
    h_cocktail_5.Scale(6492./h_cocktail_5.Integral())
    h_cocktail_1.Draw("HIST")
    h_cocktail_2.Draw("HIST same")
    h_cocktail_3.Draw("HIST same")
    h_cocktail_4.Draw("HIST same")
    h_cocktail_5.Draw("HIST same")
    leg_cocktail = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail.AddEntry(h_cocktail_1, "B^{+} #rightarrow #bar{D}^{0} D^{0} K^{+}", "fp")
    leg_cocktail.AddEntry(h_cocktail_2, "B^{+} #rightarrow D^{+} D^{-} K^{+}", "fp")
    leg_cocktail.AddEntry(h_cocktail_3, "B^{+} #rightarrow D^{+}_{s} D^{-}_{s} K^{+}", "fp")
    leg_cocktail.AddEntry(h_cocktail_4, "B^{0} #rightarrow D^{0} D^{-} K^{+}", "fp")
    leg_cocktail.AddEntry(h_cocktail_5, "B^{0}_{s} #rightarrow D^{0} D^{-}_{s} K^{+}", "fp")
    leg_cocktail.SetBorderSize(0)
    leg_cocktail.Draw("same")
    c_cocktail.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDKp_shapes_bdt_0.0.pdf")

    h_cocktail_bdt_1 = ROOT.TH1D("h_cocktail_bdt_1", "h_cocktail_bdt_1", nbins, 4000, 9000)
    h_cocktail_bdt_2 = ROOT.TH1D("h_cocktail_bdt_2", "h_cocktail_bdt_2", nbins, 4000, 9000)
    h_cocktail_bdt_3 = ROOT.TH1D("h_cocktail_bdt_3", "h_cocktail_bdt_3", nbins, 4000, 9000)
    h_cocktail_bdt_4 = ROOT.TH1D("h_cocktail_bdt_4", "h_cocktail_bdt_4", nbins, 4000, 9000)
    h_cocktail_bdt_5 = ROOT.TH1D("h_cocktail_bdt_5", "h_cocktail_bdt_5", nbins, 4000, 9000)

    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt_1", "(species == 100) && (BDT > 0.9)")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt_2", "(species == 101) && (BDT > 0.9)")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt_3", "(species == 102) && (BDT > 0.9)")
    t_BdDDKp.Draw("df_Bp_M >> h_cocktail_bdt_4", "(species == 110) && (BDT > 0.9)")
    t_BsDDKp.Draw("df_Bp_M >> h_cocktail_bdt_5", "(species == 120) && (BDT > 0.9)")

    c_cocktail_bdt = ROOT.TCanvas()
    c_cocktail_bdt.cd()
    h_cocktail_bdt_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_cocktail_bdt_4.GetYaxis().SetTitle("Expected entries / (50 MeV)")
    h_cocktail_bdt_4.SetTitle("BDT > 0.9")
    h_cocktail_bdt_1.SetLineColor(1)
    h_cocktail_bdt_2.SetLineColor(4)
    h_cocktail_bdt_3.SetLineColor(2)
    h_cocktail_bdt_4.SetLineColor(8)
    h_cocktail_bdt_5.SetLineColor(6)
    h_cocktail_bdt_1.Scale(1427./h_cocktail_bdt_1.Integral())    
    h_cocktail_bdt_2.Scale(377./h_cocktail_bdt_2.Integral())    
    h_cocktail_bdt_3.Scale(143./h_cocktail_bdt_3.Integral())    
    h_cocktail_bdt_4.Scale(1814./h_cocktail_bdt_4.Integral())    
    h_cocktail_bdt_5.Scale(775./h_cocktail_bdt_5.Integral())
    h_cocktail_bdt_4.Draw("HIST")
    h_cocktail_bdt_1.Draw("HIST same")
    h_cocktail_bdt_2.Draw("HIST same")
    h_cocktail_bdt_3.Draw("HIST same")
    h_cocktail_bdt_5.Draw("HIST same")
    leg_cocktail_bdt = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail_bdt.AddEntry(h_cocktail_bdt_1, "B^{+} #rightarrow #bar{D}^{0} D^{0} K^{+}", "fp")
    leg_cocktail_bdt.AddEntry(h_cocktail_bdt_2, "B^{+} #rightarrow D^{+} D^{-} K^{+}", "fp")
    leg_cocktail_bdt.AddEntry(h_cocktail_bdt_3, "B^{+} #rightarrow D^{+}_{s} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_bdt.AddEntry(h_cocktail_bdt_4, "B^{0} #rightarrow D^{0} D^{-} K^{+}", "fp")
    leg_cocktail_bdt.AddEntry(h_cocktail_bdt_5, "B^{0}_{s} #rightarrow D^{0} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_bdt.SetBorderSize(0)
    leg_cocktail_bdt.Draw("same")
    c_cocktail_bdt.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDKp_shapes_bdt_0.9.pdf")

    h_cocktail_bdt1_1 = ROOT.TH1D("h_cocktail_bdt1_1", "h_cocktail_bdt1_1", nbins, 4000, 9000)
    h_cocktail_bdt1_2 = ROOT.TH1D("h_cocktail_bdt1_2", "h_cocktail_bdt1_2", nbins, 4000, 9000)
    h_cocktail_bdt1_3 = ROOT.TH1D("h_cocktail_bdt1_3", "h_cocktail_bdt1_3", nbins, 4000, 9000)
    h_cocktail_bdt1_4 = ROOT.TH1D("h_cocktail_bdt1_4", "h_cocktail_bdt1_4", nbins, 4000, 9000)
    h_cocktail_bdt1_5 = ROOT.TH1D("h_cocktail_bdt1_5", "h_cocktail_bdt1_5", nbins, 4000, 9000)

    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt1_1", "(species == 100) && (BDT > 0.999)")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt1_2", "(species == 101) && (BDT > 0.999)")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt1_3", "(species == 102) && (BDT > 0.999)")
    t_BdDDKp.Draw("df_Bp_M >> h_cocktail_bdt1_4", "(species == 110) && (BDT > 0.999)")
    t_BsDDKp.Draw("df_Bp_M >> h_cocktail_bdt1_5", "(species == 120) && (BDT > 0.999)")

    c_cocktail_bdt1 = ROOT.TCanvas()
    c_cocktail_bdt1.cd()
    h_cocktail_bdt1_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_cocktail_bdt1_4.GetYaxis().SetTitle("Expected entries / (50 MeV)")
    h_cocktail_bdt1_4.SetTitle("BDT > 0.999")
    h_cocktail_bdt1_1.SetLineColor(1)
    h_cocktail_bdt1_2.SetLineColor(4)
    h_cocktail_bdt1_3.SetLineColor(2)
    h_cocktail_bdt1_4.SetLineColor(8)
    h_cocktail_bdt1_5.SetLineColor(6)
    h_cocktail_bdt1_1.Scale(8./h_cocktail_bdt1_1.Integral())    
    h_cocktail_bdt1_2.Scale(9/h_cocktail_bdt1_2.Integral())    
    h_cocktail_bdt1_3.Scale(1./h_cocktail_bdt1_3.Integral())    
    h_cocktail_bdt1_4.Scale(16./h_cocktail_bdt1_4.Integral())    
    h_cocktail_bdt1_5.Scale(12./h_cocktail_bdt1_5.Integral())
    h_cocktail_bdt1_4.Draw("HIST")
    h_cocktail_bdt1_1.Draw("HIST same")
    h_cocktail_bdt1_2.Draw("HIST same")
    h_cocktail_bdt1_3.Draw("HIST same")
    h_cocktail_bdt1_5.Draw("HIST same")
    leg_cocktail_bdt1 = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail_bdt1.AddEntry(h_cocktail_bdt1_1, "B^{+} #rightarrow #bar{D}^{0} D^{0} K^{+}", "fp")
    leg_cocktail_bdt1.AddEntry(h_cocktail_bdt1_2, "B^{+} #rightarrow D^{+} D^{-} K^{+}", "fp")
    leg_cocktail_bdt1.AddEntry(h_cocktail_bdt1_3, "B^{+} #rightarrow D^{+}_{s} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_bdt1.AddEntry(h_cocktail_bdt1_4, "B^{0} #rightarrow D^{0} D^{-} K^{+}", "fp")
    leg_cocktail_bdt1.AddEntry(h_cocktail_bdt1_5, "B^{0}_{s} #rightarrow D^{0} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_bdt1.SetBorderSize(0)
    leg_cocktail_bdt1.Draw("same")
    c_cocktail_bdt1.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDKp_shapes_bdt_0.999.pdf")

    h_cocktail_bdt2_1 = ROOT.TH1D("h_cocktail_bdt2_1", "h_cocktail_bdt2_1", nbins, 4000, 9000)
    h_cocktail_bdt2_2 = ROOT.TH1D("h_cocktail_bdt2_2", "h_cocktail_bdt2_2", nbins, 4000, 9000)
    h_cocktail_bdt2_3 = ROOT.TH1D("h_cocktail_bdt2_3", "h_cocktail_bdt2_3", nbins, 4000, 9000)
    h_cocktail_bdt2_4 = ROOT.TH1D("h_cocktail_bdt2_4", "h_cocktail_bdt2_4", nbins, 4000, 9000)
    h_cocktail_bdt2_5 = ROOT.TH1D("h_cocktail_bdt2_5", "h_cocktail_bdt2_5", nbins, 4000, 9000)

    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt2_1", "(species == 100) && (BDT > 0.99)")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt2_2", "(species == 101) && (BDT > 0.99)")
    t_BuDDKp.Draw("df_Bp_M >> h_cocktail_bdt2_3", "(species == 102) && (BDT > 0.99)")
    t_BdDDKp.Draw("df_Bp_M >> h_cocktail_bdt2_4", "(species == 110) && (BDT > 0.99)")
    t_BsDDKp.Draw("df_Bp_M >> h_cocktail_bdt2_5", "(species == 120) && (BDT > 0.99)")

    c_cocktail_bdt2 = ROOT.TCanvas()
    c_cocktail_bdt2.cd()
    h_cocktail_bdt2_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_cocktail_bdt2_4.GetYaxis().SetTitle("Expected entries / (50 MeV)")
    h_cocktail_bdt2_4.SetTitle("BDT > 0.99")
    h_cocktail_bdt2_1.SetLineColor(1)
    h_cocktail_bdt2_2.SetLineColor(4)
    h_cocktail_bdt2_3.SetLineColor(2)
    h_cocktail_bdt2_4.SetLineColor(8)
    h_cocktail_bdt2_5.SetLineColor(6)
    h_cocktail_bdt2_1.Scale(206./h_cocktail_bdt2_1.Integral())    
    h_cocktail_bdt2_2.Scale(124./h_cocktail_bdt2_2.Integral())    
    h_cocktail_bdt2_3.Scale(18./h_cocktail_bdt2_3.Integral())    
    h_cocktail_bdt2_4.Scale(374./h_cocktail_bdt2_4.Integral())    
    h_cocktail_bdt2_5.Scale(127./h_cocktail_bdt2_5.Integral())
    h_cocktail_bdt2_4.Draw("HIST")
    h_cocktail_bdt2_1.Draw("HIST same")
    h_cocktail_bdt2_2.Draw("HIST same")
    h_cocktail_bdt2_3.Draw("HIST same")
    h_cocktail_bdt2_5.Draw("HIST same")
    leg_cocktail_bdt2 = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail_bdt2.AddEntry(h_cocktail_bdt2_1, "B^{+} #rightarrow #bar{D}^{0} D^{0} K^{+}", "fp")
    leg_cocktail_bdt2.AddEntry(h_cocktail_bdt2_2, "B^{+} #rightarrow D^{+} D^{-} K^{+}", "fp")
    leg_cocktail_bdt2.AddEntry(h_cocktail_bdt2_3, "B^{+} #rightarrow D^{+}_{s} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_bdt2.AddEntry(h_cocktail_bdt2_4, "B^{0} #rightarrow D^{0} D^{-} K^{+}", "fp")
    leg_cocktail_bdt2.AddEntry(h_cocktail_bdt2_5, "B^{0}_{s} #rightarrow D^{0} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_bdt2.SetBorderSize(0)
    leg_cocktail_bdt2.Draw("same")
    c_cocktail_bdt2.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDKp_shapes_bdt_0.99.pdf")

    h_cocktail_x_1 = ROOT.TH1D("h_cocktail_x_1", "h_cocktail_x_1", nbins, 4000, 9000)
    h_cocktail_x_2 = ROOT.TH1D("h_cocktail_x_2", "h_cocktail_x_2", nbins, 4000, 9000)
    h_cocktail_x_3 = ROOT.TH1D("h_cocktail_x_3", "h_cocktail_x_3", nbins, 4000, 9000)
    h_cocktail_x_4 = ROOT.TH1D("h_cocktail_x_4", "h_cocktail_x_4", nbins, 4000, 9000)

    t_BuDDK0.Draw("df_Bp_M >> h_cocktail_x_1", "species == 130")
    t_BuDD.Draw("df_Bp_M >> h_cocktail_x_2", "species == 150")
    t_BuDD.Draw("df_Bp_M >> h_cocktail_x_3", "species == 151")
    t_ws.Draw("df_Bp_M >> h_cocktail_x_4")

    c_cocktail_x = ROOT.TCanvas()
    c_cocktail_x.SetLogy()
    c_cocktail_x.cd()
    h_cocktail_x_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_cocktail_x_4.GetYaxis().SetTitle("Normalized entries / (50 MeV)")
    h_cocktail_x_4.SetTitle("Before BDT cuts")
    h_cocktail_x_1.SetLineColor(1)
    h_cocktail_x_2.SetLineColor(4)
    h_cocktail_x_3.SetLineColor(2)
    h_cocktail_x_4.SetLineColor(8)
    h_cocktail_x_1.Scale(2699./h_cocktail_x_1.Integral())
    h_cocktail_x_2.Scale(63736./h_cocktail_x_2.Integral())
    h_cocktail_x_3.Scale(1528./h_cocktail_x_3.Integral())
    h_cocktail_x_4.Scale(N_comb_00/h_cocktail_x_4.Integral())
    h_cocktail_x_4.Draw("HIST")
    h_cocktail_x_1.Draw("HIST same")
    h_cocktail_x_2.Draw("HIST same")
    h_cocktail_x_3.Draw("HIST same")
    leg_cocktail_x = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail_x.AddEntry(h_cocktail_x_1, "B^{+} #rightarrow #bar{D}^{0} D^{+} K^{0}", "fp")
    leg_cocktail_x.AddEntry(h_cocktail_x_2, "B^{+} #rightarrow #bar{D}^{0} D^{+}_{s}", "fp")
    leg_cocktail_x.AddEntry(h_cocktail_x_3, "B^{+} #rightarrow #bar{D}^{0} D^{+}", "fp")
    leg_cocktail_x.AddEntry(h_cocktail_x_4, "Combinatorial (WS data)", "fp")
    leg_cocktail_x.SetBorderSize(0)
    leg_cocktail_x.Draw("same")
    c_cocktail_x.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDX_shapes_bdt_0.0.pdf")

    h_cocktail_bdt_x_1 = ROOT.TH1D("h_cocktail_bdt_x_1", "h_cocktail_bdt_x_1", nbins, 4000, 9000)
    h_cocktail_bdt_x_2 = ROOT.TH1D("h_cocktail_bdt_x_2", "h_cocktail_bdt_x_2", nbins, 4000, 9000)
    h_cocktail_bdt_x_3 = ROOT.TH1D("h_cocktail_bdt_x_3", "h_cocktail_bdt_x_3", nbins, 4000, 9000)
    h_cocktail_bdt_x_4 = ROOT.TH1D("h_cocktail_bdt_x_4", "h_cocktail_bdt_x_4", nbins, 4000, 9000)

    t_BuDDK0.Draw("df_Bp_M >> h_cocktail_bdt_x_1", "(species == 130) && (BDT > 0.9)")
    t_BuDD.Draw("df_Bp_M >> h_cocktail_bdt_x_2", "(species == 150) && (BDT > 0.9)")
    t_BuDD.Draw("df_Bp_M >> h_cocktail_bdt_x_3", "(species == 151) && (BDT > 0.9)")
    t_ws.Draw("df_Bp_M >> h_cocktail_bdt_x_4", "BDT > 0.9")

    c_cocktail_bdt_x = ROOT.TCanvas()
    c_cocktail_bdt_x.cd()
    c_cocktail_bdt_x.SetLogy()
    h_cocktail_bdt_x_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_cocktail_bdt_x_4.GetYaxis().SetTitle("Normalized entries / (50 MeV)")
    h_cocktail_bdt_x_4.SetTitle("BDT > 0.9")
    h_cocktail_bdt_x_1.SetLineColor(1)
    h_cocktail_bdt_x_2.SetLineColor(4)
    h_cocktail_bdt_x_3.SetLineColor(2)
    h_cocktail_bdt_x_4.SetLineColor(8)
    h_cocktail_bdt_x_1.Scale(146./h_cocktail_bdt_x_1.Integral())
    h_cocktail_bdt_x_2.Scale(2619./h_cocktail_bdt_x_2.Integral())
    h_cocktail_bdt_x_3.Scale(148./h_cocktail_bdt_x_3.Integral())
    h_cocktail_bdt_x_4.Scale(N_comb_09/h_cocktail_bdt_x_4.Integral())
    h_cocktail_bdt_x_4.Draw("HIST")
    h_cocktail_bdt_x_1.Draw("HIST same")
    h_cocktail_bdt_x_2.Draw("HIST same")
    h_cocktail_bdt_x_3.Draw("HIST same")
    leg_cocktail_bdt_x = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail_bdt_x.AddEntry(h_cocktail_bdt_x_1, "B^{+} #rightarrow #bar{D}^{0} D^{+} K^{0}", "fp")
    leg_cocktail_bdt_x.AddEntry(h_cocktail_bdt_x_2, "B^{+} #rightarrow #bar{D}^{0} D^{+}_{s}", "fp")
    leg_cocktail_bdt_x.AddEntry(h_cocktail_bdt_x_3, "B^{+} #rightarrow #bar{D}^{0} D^{+}", "fp")
    leg_cocktail_bdt_x.AddEntry(h_cocktail_bdt_x_4, "Combinatorial (WS data)", "fp")
    leg_cocktail_bdt_x.SetBorderSize(0)
    leg_cocktail_bdt_x.Draw("same")
    c_cocktail_bdt_x.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDX_shapes_bdt_0.9.pdf")

    # h_cocktail_bdt1_x_1 = ROOT.TH1D("h_cocktail_bdt1_x_1", "h_cocktail_bdt1_x_1", nbins, 4000, 9000)
    # h_cocktail_bdt1_x_2 = ROOT.TH1D("h_cocktail_bdt1_x_2", "h_cocktail_bdt1_x_2", nbins, 4000, 9000)
    # h_cocktail_bdt1_x_3 = ROOT.TH1D("h_cocktail_bdt1_x_3", "h_cocktail_bdt1_x_3", nbins, 4000, 9000)
    # h_cocktail_bdt1_x_4 = ROOT.TH1D("h_cocktail_bdt1_x_4", "h_cocktail_bdt1_x_4", nbins, 4000, 9000)

    # t_BuDDK0.Draw("df_Bp_M >> h_cocktail_bdt1_x_1", "(species == 130) && (BDT > 0.999)")
    # t_BuDD.Draw("df_Bp_M >> h_cocktail_bdt1_x_2", "(species == 150) && (BDT > 0.999)")
    # t_BuDD.Draw("df_Bp_M >> h_cocktail_bdt1_x_3", "(species == 151) && (BDT > 0.999)")
    # t_ws.Draw("df_Bp_M >> h_cocktail_bdt1_x_4", "BDT > 0.999")

    # c_cocktail_bdt1_x = ROOT.TCanvas()
    # c_cocktail_bdt1_x.cd()
    # c_cocktail_bdt1_x.SetLogy()
    # h_cocktail_bdt1_x_4.GetXaxis().SetTitle("m_{B} (MeV)")
    # h_cocktail_bdt1_x_4.GetYaxis().SetTitle("Normalized entries / (50 MeV)")
    # h_cocktail_bdt1_x_4.SetTitle("BDT > 0.999")
    # h_cocktail_bdt1_x_1.SetLineColor(1)
    # h_cocktail_bdt1_x_2.SetLineColor(4)
    # h_cocktail_bdt1_x_3.SetLineColor(2)
    # h_cocktail_bdt1_x_4.SetLineColor(8)
    # h_cocktail_bdt1_x_1.Scale(0)
    # h_cocktail_bdt1_x_2.Scale(0)
    # h_cocktail_bdt1_x_3.Scale(0)
    # h_cocktail_bdt1_x_4.Scale(N_comb_0999/h_cocktail_bdt1_x_4.Integral())
    # h_cocktail_bdt1_x_4.Draw("HIST")
    # h_cocktail_bdt1_x_1.Draw("HIST same")
    # h_cocktail_bdt1_x_2.Draw("HIST same")
    # h_cocktail_bdt1_x_3.Draw("HIST same")
    # leg_cocktail_bdt1_x = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    # leg_cocktail_bdt1_x.AddEntry(h_cocktail_bdt1_x_1, "B^{+} #rightarrow #bar{D}^{0} D^{+} K^{0}", "fp")
    # leg_cocktail_bdt1_x.AddEntry(h_cocktail_bdt1_x_2, "B^{+} #rightarrow #bar{D}^{0} D^{+}_{s}", "fp")
    # leg_cocktail_bdt1_x.AddEntry(h_cocktail_bdt1_x_3, "B^{+} #rightarrow #bar{D}^{0} D^{+}", "fp")
    # leg_cocktail_bdt1_x.AddEntry(h_cocktail_bdt1_x_4, "Combinatorial (WS data)", "fp")
    # leg_cocktail_bdt1_x.SetBorderSize(0)
    # leg_cocktail_bdt1_x.Draw("same")
    # c_cocktail_bdt1_x.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDX_shapes_bdt_0.999.pdf")

    h_cocktail_bdt2_x_1 = ROOT.TH1D("h_cocktail_bdt2_x_1", "h_cocktail_bdt2_x_1", nbins, 4000, 9000)
    h_cocktail_bdt2_x_2 = ROOT.TH1D("h_cocktail_bdt2_x_2", "h_cocktail_bdt2_x_2", nbins, 4000, 9000)
    h_cocktail_bdt2_x_3 = ROOT.TH1D("h_cocktail_bdt2_x_3", "h_cocktail_bdt2_x_3", nbins, 4000, 9000)
    h_cocktail_bdt2_x_4 = ROOT.TH1D("h_cocktail_bdt2_x_4", "h_cocktail_bdt2_x_4", nbins, 4000, 9000)

    t_BuDDK0.Draw("df_Bp_M >> h_cocktail_bdt2_x_1", "(species == 130) && (BDT > 0.99)")
    t_BuDD.Draw("df_Bp_M >> h_cocktail_bdt2_x_2", "(species == 150) && (BDT > 0.99)")
    t_BuDD.Draw("df_Bp_M >> h_cocktail_bdt2_x_3", "(species == 151) && (BDT > 0.99)")
    t_ws.Draw("df_Bp_M >> h_cocktail_bdt2_x_4", "BDT > 0.999")

    c_cocktail_bdt2_x = ROOT.TCanvas()
    c_cocktail_bdt2_x.cd()
    c_cocktail_bdt2_x.SetLogy()
    h_cocktail_bdt2_x_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_cocktail_bdt2_x_4.GetYaxis().SetTitle("Normalized entries / (50 MeV)")
    h_cocktail_bdt2_x_4.SetTitle("BDT > 0.99")
    h_cocktail_bdt2_x_1.SetLineColor(1)
    h_cocktail_bdt2_x_2.SetLineColor(4)
    h_cocktail_bdt2_x_3.SetLineColor(2)
    h_cocktail_bdt2_x_4.SetLineColor(8)
    h_cocktail_bdt2_x_1.Scale(144./h_cocktail_bdt2_x_1.Integral())
    h_cocktail_bdt2_x_2.Scale(2592./h_cocktail_bdt2_x_2.Integral())
    h_cocktail_bdt2_x_3.Scale(146./h_cocktail_bdt2_x_3.Integral())
    h_cocktail_bdt2_x_4.Scale(N_comb_099/h_cocktail_bdt2_x_4.Integral())
    h_cocktail_bdt2_x_4.Draw("HIST")
    h_cocktail_bdt2_x_1.Draw("HIST same")
    h_cocktail_bdt2_x_2.Draw("HIST same")
    h_cocktail_bdt2_x_3.Draw("HIST same")
    leg_cocktail_bdt2_x = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail_bdt2_x.AddEntry(h_cocktail_bdt2_x_1, "B^{+} #rightarrow #bar{D}^{0} D^{+} K^{0}", "fp")
    leg_cocktail_bdt2_x.AddEntry(h_cocktail_bdt2_x_2, "B^{+} #rightarrow #bar{D}^{0} D^{+}_{s}", "fp")
    leg_cocktail_bdt2_x.AddEntry(h_cocktail_bdt2_x_3, "B^{+} #rightarrow #bar{D}^{0} D^{+}", "fp")
    leg_cocktail_bdt2_x.AddEntry(h_cocktail_bdt2_x_4, "Combinatorial (WS data)", "fp")
    leg_cocktail_bdt2_x.SetBorderSize(0)
    leg_cocktail_bdt2_x.Draw("same")
    c_cocktail_bdt2_x.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/BDDX_shapes_bdt_0.99.pdf")

    c_ktautau_bdt = ROOT.TCanvas()
    c_ktautau_bdt.cd()
    h_ktautau_bdt_1 = ROOT.TH1D("h_ktautau_bdt_1", "h_ktautau_bdt_1", nbins, 0, 1)
    h_ktautau_bdt_2 = ROOT.TH1D("h_ktautau_bdt_2", "h_ktautau_bdt_2", nbins, 0, 1)
    h_ktautau_bdt_3 = ROOT.TH1D("h_ktautau_bdt_3", "h_ktautau_bdt_3", nbins, 0, 1)
    t_sig.Draw("BDT >> h_ktautau_bdt_1")
    t_rs.Draw("BDT >> h_ktautau_bdt_2")
    t_ws.Draw("BDT >> h_ktautau_bdt_3")
    h_ktautau_bdt_1.SetLineColor(4)
    h_ktautau_bdt_2.SetLineColor(1)
    h_ktautau_bdt_3.SetLineColor(2)
    h_ktautau_bdt_2.GetXaxis().SetTitle("BDT")
    h_ktautau_bdt_2.GetYaxis().SetTitle("Normalized entries / (0.01)")
    h_ktautau_bdt_2.SetTitle("Ktautau")
    h_ktautau_bdt_2.DrawNormalized()
    h_ktautau_bdt_1.DrawNormalized("same")
    h_ktautau_bdt_3.DrawNormalized("same")
    leg_ktautau_bdt = ROOT.TLegend(0.6, 0.7, 0.89, 0.89)
    leg_ktautau_bdt.AddEntry(h_ktautau_bdt_1, "MC", "fp")
    leg_ktautau_bdt.AddEntry(h_ktautau_bdt_2, "RS data", "fp")
    leg_ktautau_bdt.AddEntry(h_ktautau_bdt_3, "WS data", "fp")
    leg_ktautau_bdt.SetBorderSize(0)
    leg_ktautau_bdt.Draw("same")
    c_ktautau_bdt.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/Ktautau_bdt.pdf")

    c_cocktail_BDT = ROOT.TCanvas()
    c_cocktail_BDT.cd()
    c_cocktail_BDT.SetLogy()
    h_cocktail_BDT_1 = ROOT.TH1D("h_cocktail_BDT_1", "h_cocktail_BDT_1", nbins, 0, 1)
    h_cocktail_BDT_2 = ROOT.TH1D("h_cocktail_BDT_2", "h_cocktail_BDT_2", nbins, 0, 1)
    h_cocktail_BDT_3 = ROOT.TH1D("h_cocktail_BDT_3", "h_cocktail_BDT_3", nbins, 0, 1)
    h_cocktail_BDT_4 = ROOT.TH1D("h_cocktail_BDT_4", "h_cocktail_BDT_4", nbins, 0, 1)
    h_cocktail_BDT_5 = ROOT.TH1D("h_cocktail_BDT_5", "h_cocktail_BDT_5", nbins, 0, 1)
    h_cocktail_BDT_6 = ROOT.TH1D("h_cocktail_BDT_6", "h_cocktail_BDT_6", nbins, 0, 1)
    h_cocktail_BDT_7 = ROOT.TH1D("h_cocktail_BDT_7", "h_cocktail_BDT_7", nbins, 0, 1)
    h_cocktail_BDT_8 = ROOT.TH1D("h_cocktail_BDT_8", "h_cocktail_BDT_8", nbins, 0, 1)
    t_BuDDKp.Draw("BDT >> h_cocktail_BDT_1", "species==100")
    t_BuDDKp.Draw("BDT >> h_cocktail_BDT_2", "species==101")
    t_BuDDKp.Draw("BDT >> h_cocktail_BDT_3", "species==102")
    t_BdDDKp.Draw("BDT >> h_cocktail_BDT_4", "species==110")
    t_BsDDKp.Draw("BDT >> h_cocktail_BDT_5", "species==120")
    t_BuDDK0.Draw("BDT >> h_cocktail_BDT_6", "species==130")
    t_BuDD.Draw("BDT >> h_cocktail_BDT_7", "species==150")
    t_BuDD.Draw("BDT >> h_cocktail_BDT_8", "species==151")
    h_cocktail_BDT_1.SetLineColor(4)
    h_cocktail_BDT_2.SetLineColor(1)
    h_cocktail_BDT_3.SetLineColor(2)
    h_cocktail_BDT_4.SetLineColor(8)
    h_cocktail_BDT_5.SetLineColor(9)
    h_cocktail_BDT_6.SetLineColor(94)
    h_cocktail_BDT_7.SetLineColor(6)
    h_cocktail_BDT_8.SetLineColor(433)
    h_cocktail_BDT_8.GetXaxis().SetTitle("BDT")
    h_cocktail_BDT_8.GetYaxis().SetTitle("Normalized entries / (0.01)")
    h_cocktail_BDT_8.SetTitle("Cocktail MCs")
    h_cocktail_BDT_8.DrawNormalized()
    h_cocktail_BDT_2.DrawNormalized("same")
    h_cocktail_BDT_3.DrawNormalized("same")
    h_cocktail_BDT_4.DrawNormalized("same")
    h_cocktail_BDT_5.DrawNormalized("same")
    h_cocktail_BDT_6.DrawNormalized("same")
    h_cocktail_BDT_7.DrawNormalized("same")
    h_cocktail_BDT_1.DrawNormalized("same")
    leg_cocktail_BDT = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_1, "B^{+} #rightarrow #bar{D}^{0} D^{0} K^{+}", "fp")
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_2, "B^{+} #rightarrow D^{+} D^{-} K^{+}", "fp")
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_3, "B^{+} #rightarrow D^{+}_{s} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_4, "B^{0} #rightarrow D^{0} D^{-} K^{+}", "fp")
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_5, "B^{0}_{s} #rightarrow D^{0} D^{-}_{s} K^{+}", "fp")
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_6, "B^{+} #rightarrow #bar{D}^{0} D^{+} K^{0}", "fp")
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_7, "B^{+} #rightarrow #bar{D}^{0} D^{+}_{s}", "fp")
    leg_cocktail_BDT.AddEntry(h_cocktail_BDT_8, "B^{+} #rightarrow #bar{D}^{0} D^{+}", "fp")
    leg_cocktail_BDT.SetBorderSize(0)
    leg_cocktail_BDT.Draw("same")
    c_cocktail_BDT.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/cocktail_bdt.pdf")


    # Signal
    h_sig_1 = ROOT.TH1D("h_sig_1", "h_sig_1", nbins, 4000, 9000)
    h_sig_2 = ROOT.TH1D("h_sig_2", "h_sig_2", nbins, 4000, 9000)
    h_sig_3 = ROOT.TH1D("h_sig_3", "h_sig_3", nbins, 4000, 9000)
    h_sig_4 = ROOT.TH1D("h_sig_4", "h_sig_4", nbins, 4000, 9000)

    t_sig.Draw("df_Bp_M >> h_sig_1", "BDT > 0.9")
    t_sig.Draw("df_Bp_M >> h_sig_2", "BDT > 0.99")
    t_sig.Draw("df_Bp_M >> h_sig_3", "BDT > 0.999")
    t_sig.Draw("df_Bp_M >> h_sig_4", "BDT > 0.9995")

    h_sig_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_sig_4.GetYaxis().SetTitle(f"Normalised entries / ( {5000/nbins:.2f} MeV)")
    h_sig_4.SetTitle("Signal template")
    h_sig_1.SetLineColor(1)
    h_sig_2.SetLineColor(4)
    h_sig_3.SetLineColor(8)
    h_sig_4.SetLineColor(2)

    leg_sig = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_sig.AddEntry(h_sig_1, "BDT > 0.9", "fp")
    leg_sig.AddEntry(h_sig_2, f"BDT > 0.99 | KS = {h_sig_2.KolmogorovTest(h_sig_1):.2f}", "fp")
    leg_sig.AddEntry(h_sig_3, f"BDT > 0.999 | KS = {h_sig_3.KolmogorovTest(h_sig_2):.2f}", "fp")
    leg_sig.AddEntry(h_sig_4, f"BDT > 0.9995 | KS = {h_sig_4.KolmogorovTest(h_sig_3):.2f}", "fp")

    c_sig = ROOT.TCanvas()
    c_sig.cd()
    h_sig_4.DrawNormalized("E")
    h_sig_3.DrawNormalized("E same")
    h_sig_2.DrawNormalized("E same")
    h_sig_1.DrawNormalized("E same")
    leg_sig.SetBorderSize(0)
    leg_sig.SetTextSize(0.03)
    leg_sig.Draw("same")
    c_sig.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/signal_template_high_bdt.pdf")

    # Physics (B -> DD K+)
    h_phys_1 = ROOT.TH1D("h_phys_1", "h_phys_1", nbins, 4000, 9000)
    h_phys_2 = ROOT.TH1D("h_phys_2", "h_phys_2", nbins, 4000, 9000)
    h_phys_3 = ROOT.TH1D("h_phys_3", "h_phys_3", nbins, 4000, 9000)
    h_phys_4 = ROOT.TH1D("h_phys_4", "h_phys_4", nbins, 4000, 9000)

    t_BDDKp.Draw("df_Bp_M >> h_phys_1", "BDT > 0.9")
    t_BDDKp.Draw("df_Bp_M >> h_phys_2", "BDT > 0.99")
    t_BDDKp.Draw("df_Bp_M >> h_phys_3", "BDT > 0.995")
    t_BDDKp.Draw("df_Bp_M >> h_phys_4", "BDT > 0.999")

    h_phys_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_phys_4.GetYaxis().SetTitle(f"Normalised entries / ( {5000/nbins:.2f} MeV)")
    h_phys_4.SetTitle("B -> DD K^{+} template")
    h_phys_1.SetLineColor(1)
    h_phys_2.SetLineColor(4)
    h_phys_3.SetLineColor(8)
    h_phys_4.SetLineColor(2)

    leg_phys = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_phys.AddEntry(h_phys_1, "BDT > 0.9", "fp")
    leg_phys.AddEntry(h_phys_2, f"BDT > 0.99 | KS = {h_phys_2.KolmogorovTest(h_phys_1):.2f}", "fp")
    leg_phys.AddEntry(h_phys_3, f"BDT > 0.995 | KS = {h_phys_3.KolmogorovTest(h_phys_2):.2f}", "fp")
    leg_phys.AddEntry(h_phys_4, f"BDT > 0.999 | KS = {h_phys_4.KolmogorovTest(h_phys_3):.2f}", "fp")

    c_phys = ROOT.TCanvas()
    c_phys.cd()
    h_phys_4.DrawNormalized("E")
    h_phys_3.DrawNormalized("E same")
    h_phys_2.DrawNormalized("E same")
    h_phys_1.DrawNormalized("E same")
    leg_phys.SetBorderSize(0)
    leg_phys.SetTextSize(0.03)
    leg_phys.Draw("same")
    c_phys.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/physics_BDDKp_template_high_bdt.pdf")


    # Combinatorial
    h_comb_1 = ROOT.TH1D("h_comb_1", "h_comb_1", nbins, 4000, 9000)
    h_comb_2 = ROOT.TH1D("h_comb_2", "h_comb_2", nbins, 4000, 9000)
    h_comb_3 = ROOT.TH1D("h_comb_3", "h_comb_3", nbins, 4000, 9000)
    h_comb_4 = ROOT.TH1D("h_comb_4", "h_comb_4", nbins, 4000, 9000)

    t_ws.Draw("df_Bp_M >> h_comb_1", "BDT > 0.9")
    t_ws.Draw("df_Bp_M >> h_comb_2", "BDT > 0.99")
    t_ws.Draw("df_Bp_M >> h_comb_3", "BDT > 0.995")
    t_ws.Draw("df_Bp_M >> h_comb_4", "BDT > 0.999")

    h_comb_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_comb_4.GetYaxis().SetTitle(f"Normalised entries / ( {5000/nbins:.2f} MeV)")
    h_comb_4.SetTitle("Combinatorial template")
    h_comb_1.SetLineColor(1)
    h_comb_2.SetLineColor(4)
    h_comb_3.SetLineColor(8)
    h_comb_4.SetLineColor(2)

    leg_comb = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_comb.AddEntry(h_comb_1, "BDT > 0.9", "fp")
    leg_comb.AddEntry(h_comb_2, f"BDT > 0.99 | KS = {h_comb_2.KolmogorovTest(h_comb_1):.2f}", "fp")
    leg_comb.AddEntry(h_comb_3, f"BDT > 0.995 | KS = {h_comb_3.KolmogorovTest(h_comb_2):.2f}", "fp")
    leg_comb.AddEntry(h_comb_4, f"BDT > 0.999 | KS = {h_comb_4.KolmogorovTest(h_comb_3):.2f}", "fp")

    c_comb = ROOT.TCanvas()
    c_comb.cd()
    h_comb_4.DrawNormalized("E")
    h_comb_3.DrawNormalized("E same")
    h_comb_2.DrawNormalized("E same")
    h_comb_1.DrawNormalized("E same")
    leg_comb.SetBorderSize(0)
    leg_comb.SetTextSize(0.03)
    leg_comb.Draw("same")
    c_comb.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/combinatorial_template_high_bdt.pdf")


    # RS data sidebands
    h_rs_1 = ROOT.TH1D("h_rs_1", "h_rs_1", nbins, 4000, 9000)
    h_rs_2 = ROOT.TH1D("h_rs_2", "h_rs_2", nbins, 4000, 9000)
    h_rs_3 = ROOT.TH1D("h_rs_3", "h_rs_3", nbins, 4000, 9000)
    h_rs_4 = ROOT.TH1D("h_rs_4", "h_rs_4", nbins, 4000, 9000)

    t_rs.Draw("df_Bp_M >> h_rs_1", "(BDT > 0.9) && ((df_Bp_M < 5000) || (df_Bp_M > 6500))")
    t_rs.Draw("df_Bp_M >> h_rs_2", "(BDT > 0.99) && ((df_Bp_M < 5000) || (df_Bp_M > 6500))")
    t_rs.Draw("df_Bp_M >> h_rs_3", "(BDT > 0.995) && ((df_Bp_M < 5000) || (df_Bp_M > 6500))")
    t_rs.Draw("df_Bp_M >> h_rs_4", "(BDT > 0.999) && ((df_Bp_M < 5000) || (df_Bp_M > 6500))")

    h_rs_4.GetXaxis().SetTitle("m_{B} (MeV)")
    h_rs_4.GetYaxis().SetTitle(f"Normalised entries / ( {5000/nbins:.2f} MeV)")
    h_rs_4.SetTitle("RS data sidebands")
    h_rs_1.SetLineColor(1)
    h_rs_2.SetLineColor(4)
    h_rs_3.SetLineColor(8)
    h_rs_4.SetLineColor(2)

    leg_rs = ROOT.TLegend(0.6, 0.5, 0.89, 0.89)
    leg_rs.AddEntry(h_rs_1, "BDT > 0.9", "fp")
    leg_rs.AddEntry(h_rs_2, f"BDT > 0.99 | KS = {h_rs_2.KolmogorovTest(h_rs_1):.2f}", "fp")
    leg_rs.AddEntry(h_rs_3, f"BDT > 0.995 | KS = {h_rs_3.KolmogorovTest(h_rs_2):.2f}", "fp")
    leg_rs.AddEntry(h_rs_4, f"BDT > 0.999 | KS = {h_rs_4.KolmogorovTest(h_rs_3):.2f}", "fp")

    c_rs = ROOT.TCanvas()
    c_rs.cd()
    h_rs_4.DrawNormalized("E")
    h_rs_3.DrawNormalized("E same")
    h_rs_2.DrawNormalized("E same")
    h_rs_1.DrawNormalized("E same")
    leg_rs.SetBorderSize(0)
    leg_rs.SetTextSize(0.03)
    leg_rs.Draw("same")
    c_rs.SaveAs("/panfs/felician/B2Ktautau/workflow/templates_choice/rs_data_sidebands_high_bdt.pdf")


    # PLOTS: RS/WS BDT efficiency vs BDT cut
    bdt_cuts = [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    BDDKp_yields = [31668, 22372, 18719, 16101, 14067, 12339, 10716, 9113, 7300, 4958]

    N = len(bdt_cuts)

    N_rs_den = t_rs.GetEntries() - BDDKp_yields[0]
    N_ws_den = t_ws.GetEntries()
    N_rs_upper_den = t_rs.GetEntries("df_Bp_M > 6500")
    N_ws_upper_den = t_ws.GetEntries("df_Bp_M > 6500")

    bdt_eff_ratio = np.zeros(N)
    bdt_eff_ratio_err = np.zeros(N)

    bdt_eff_ratio_upper = np.zeros(N)
    bdt_eff_ratio_upper_err = np.zeros(N)

    for i in range(N):
        print("BDT > {0}".format(bdt_cuts[i]))

        N_rs_num = t_rs.GetEntries(f"BDT > {bdt_cuts[i]}") - BDDKp_yields[i]
        N_ws_num = t_ws.GetEntries(f"BDT > {bdt_cuts[i]}")
        N_rs_upper_num = t_rs.GetEntries(f"BDT > {bdt_cuts[i]} && (df_Bp_M > 6500)")
        N_ws_upper_num = t_ws.GetEntries(f"BDT > {bdt_cuts[i]} && (df_Bp_M > 6500)")

        eps_rs = N_rs_num/N_rs_den
        eps_rs_up = ROOT.TEfficiency.Wilson(N_rs_den, N_rs_num, 0.68, True)
        eps_rs_down = ROOT.TEfficiency.Wilson(N_rs_den, N_rs_num, 0.68, False)
        eps_rs_err = 0.5*(eps_rs_up-eps_rs_down)
        eps_rs = ufloat(eps_rs, eps_rs_err)

        eps_ws = N_ws_num/N_ws_den
        eps_ws_up = ROOT.TEfficiency.Wilson(N_ws_den, N_ws_num, 0.68, True)
        eps_ws_down = ROOT.TEfficiency.Wilson(N_ws_den, N_ws_num, 0.68, False)
        eps_ws_err = 0.5*(eps_ws_up-eps_ws_down)
        eps_ws = ufloat(eps_ws, eps_ws_err)

        eps_rs_upper = N_rs_upper_num/N_rs_upper_den
        eps_rs_up_upper = ROOT.TEfficiency.Wilson(N_rs_upper_den, N_rs_upper_num, 0.68, True)
        eps_rs_down_upper = ROOT.TEfficiency.Wilson(N_rs_upper_den, N_rs_upper_num, 0.68, False)
        eps_rs_err_upper = 0.5*(eps_rs_up_upper-eps_rs_down_upper)
        eps_rs_upper = ufloat(eps_rs_upper, eps_rs_err_upper)

        eps_ws_upper = N_ws_upper_num/N_ws_upper_den
        eps_ws_up_upper = ROOT.TEfficiency.Wilson(N_ws_upper_den, N_ws_upper_num, 0.68, True)
        eps_ws_down_upper = ROOT.TEfficiency.Wilson(N_ws_upper_den, N_ws_upper_num, 0.68, False)
        eps_ws_err_upper = 0.5*(eps_ws_up_upper-eps_ws_down_upper)
        eps_ws_upper = ufloat(eps_ws_upper, eps_ws_err_upper)

        bdt_eff_ratio[i] = (eps_rs/eps_ws).nominal_value
        bdt_eff_ratio_err[i] = (eps_rs/eps_ws).std_dev
        bdt_eff_ratio_upper[i] = (eps_rs_upper/eps_ws_upper).nominal_value
        bdt_eff_ratio_upper_err[i] = (eps_rs_upper/eps_ws_upper).std_dev

    plt.errorbar(bdt_cuts, bdt_eff_ratio, yerr=bdt_eff_ratio_err, marker="o")
    # plt.errorbar(bdt_cuts, bdt_eff_ratio_upper, yerr=bdt_eff_ratio_upper_err, label="BDT eff ratio (upper sideband)", marker="o")
    plt.xlabel("BDT cut")
    plt.ylabel("(RS-BDDK+)/WS BDT efficiency ratio")
    # plt.legend()
    plt.savefig("/panfs/felician/B2Ktautau/workflow/templates_choice/rs_vs_ws_bdt_eff.pdf")
    plt.clf()

    plt.plot(bdt_cuts, bdt_eff_ratio_upper/bdt_eff_ratio)
    plt.xlabel('BDT cut')
    plt.ylabel('BDT eff ratio in fit range / upper sideband')
    plt.savefig("/panfs/felician/B2Ktautau/workflow/templates_choice/ratio_of_ratio.pdf")
    plt.clf()

    bdt_cuts_1 = [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.96, 0.961, 0.962, 0.963, 0.964, 0.965, 0.966, 0.967, 0.968, 0.969, 0.97]

    N1 = len(bdt_cuts_1)

    ws_eff = np.zeros(N1)
    ws_eff_err = np.zeros(N1)

    for i in range(N1):
        print("BDT > {0}".format(bdt_cuts_1[i]))

        N_ws_num = t_ws.GetEntries(f"BDT > {bdt_cuts_1[i]}")
        ws_eff[i] = N_ws_num/N_ws_den

        ws_eff_up = ROOT.TEfficiency.Wilson(N_ws_den, N_ws_num, 0.68, True)
        ws_eff_down = ROOT.TEfficiency.Wilson(N_ws_den, N_ws_num, 0.68, False)
        ws_eff_err[i] = 0.5*(ws_eff_up-ws_eff_down)
    

    plt.errorbar(bdt_cuts_1, ws_eff, yerr=ws_eff_err, marker=".")
    plt.xlabel("BDT cut")
    plt.ylabel("WS BDT efficiency ratio")
    plt.grid()
    plt.savefig("/panfs/felician/B2Ktautau/workflow/templates_choice/ws_bdt_eff.pdf")
    plt.clf()


if __name__ == "__main__":
    main(sys.argv)